# Generated by Django 4.1.6 on 2023-04-19 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_rename_school_student_school_name_student_standard"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
